security:
    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext
#            algorithm: bcrypt
#            cost: 12
#        default:
#            algorithm: sha512

    providers:
        orm:
            entity:
                class: AppBundle:User
                property: username

#    firewalls:
#        login_firewall:
#            pattern:   ^/login$
#            anonymous:
#            logout:       true
#            anonymous:    true

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login_firewall:

        default:
            pattern:   ^/
            logout:       true
            anonymous:    true
            provider: orm
            form_login:
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /chat
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/chat, role: ROLE_USER }
        - { path: ^/show, role: ROLE_USER }
        - { path: ^/new, role: ROLE_USER }
        - { path: ^/message, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }



